spring.datasource.url=jdbc:postgresql://localhost:5432/shopsphere
spring.datasource.username=postgres
spring.datasource.password=S@nDaRU#97

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt.secret=Z5JgcNvh0nYxRiMZCXyjQEb8v/caF1mzsvj7eVTGTrQ=
jwt.expiration=3600000